<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Francisco_Gomes/atividade_09_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

filtragem de elementos com pandas

In [4]:
import pandas as pd
brics = pd.read_csv("https://drive.usercontent.google.com/download?id=1AyKIujQCftGvsAZRMjrHBj8pSXPAzRq_&export=download&authuser=1", index_col = 0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [5]:
brics["population"]

country_ab
BR     200.40
RU     143.50
IN    1252.00
CH    1357.00
SA      52.98
Name: population, dtype: float64

In [6]:
brics["population"] > 1000

country_ab
BR    False
RU    False
IN     True
CH     True
SA    False
Name: population, dtype: bool

In [8]:
is_huge = brics["population"] > 1000
brics[is_huge]

           country    capital   area  population
country_ab
IN           India  New Delhi  3.286      1252.0
CH           China    Beijing  9.597      1357.0

In [13]:
import pandas as np
cars = pd.read_csv("https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1", index_col =0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [19]:
#mostrar apenas a coluna drives_right.
dr = cars["drives_right"] == True
sel = cars[dr]
sel

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [20]:
cars[cars["drives_right"] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [23]:
cars[cars["cars_per_cap"] < 100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

In [25]:
offset = 10

while offset !=  0:
      offset = offset - 1
      print(offset)

9
8
7
6
5
4
3
2
1
0