<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula10.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS

*Acesso as colunas - Observe a última linha. Não é um dataframe*

In [1]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [2]:
brics['country']

country_ab
BR          Brazil
RU          Russia
IN           India
CH           China
SA    South Africa
Name: country, dtype: object

In [3]:
type(brics['country'])

pandas.core.series.Series

In [5]:
brics[['country']]

                 country
country_ab
BR                Brazil
RU                Russia
IN                 India
CH                 China
SA          South Africa

In [6]:
type(brics[['country']])

pandas.core.frame.DataFrame

In [7]:
brics[['country', 'capital']]

                 country    capital
country_ab
BR                Brazil   Brasilia
RU                Russia     Moscow
IN                 India  New Delhi
CH                 China    Beijing
SA          South Africa   Pretoria

*Pandas - Acesso a linhas*

In [9]:
brics[1:4]

           country    capital    area  population
country_ab
RU          Russia     Moscow  17.100       143.5
IN           India  New Delhi   3.286      1252.0
CH           China    Beijing   9.597      1357.0

*Pandas - Acesso às linhas pela função loc*

In [11]:
brics.loc['RU']

country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object

In [12]:
brics.loc[['RU']] #irá deixar tudo em uma só linha.

           country capital  area  population
country_ab
RU          Russia  Moscow  17.1       143.5

*Pandas - cont.: Acesso a linhas*

In [13]:
brics.loc[['RU', 'IN', 'CH']]

           country    capital    area  population
country_ab
RU          Russia     Moscow  17.100       143.5
IN           India  New Delhi   3.286      1252.0
CH           China    Beijing   9.597      1357.0

*Pandas - Acesso a linhas e colunas*

In [14]:
brics.loc[['RU', 'IN', 'CH'], ['country', 'capital']]

           country    capital
country_ab
RU          Russia     Moscow
IN           India  New Delhi
CH           China    Beijing

In [15]:
brics.loc[:, ['country', 'capital']]

                 country    capital
country_ab
BR                Brazil   Brasilia
RU                Russia     Moscow
IN                 India  New Delhi
CH                 China    Beijing
SA          South Africa   Pretoria

*Pandas - Acesso à linhas pelo iloc*

In [16]:
brics.iloc[[1]] #daria o mesmo resultado se fizesse -> brics.loc[['RU']]

           country capital  area  population
country_ab
RU          Russia  Moscow  17.1       143.5

In [17]:
brics.iloc[[1, 2, 3]]

           country    capital    area  population
country_ab
RU          Russia     Moscow  17.100       143.5
IN           India  New Delhi   3.286      1252.0
CH           China    Beijing   9.597      1357.0

*Pandas - Acesso a linhas e colunas pelo iloc*

In [18]:
brics.iloc[[1, 2, 3], [0, 1]]

           country    capital
country_ab
RU          Russia     Moscow
IN           India  New Delhi
CH           China    Beijing