<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/hugo_alexandre/aula12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/brics.csv", index_col = 0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics["area"]>8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = brics["area"]>8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
brics[brics["area"]>8]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
import pandas as pd

cars = pd.read_csv('cars.csv', index_col = 0)
dr = cars["drives_right"]==True
sel = cars[dr]
sel          #pq print de dr da diferente? sel = tabela// pesquuisar

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars["drives_right"]==True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
error = 50.0
# 3.125
while error >1:  #True
 error = error / 4
 print(error)

12.5
3.125
0.78125

In [ ]:
#crie uma variável offset. Inicialize ela igual 10.
offset = 10
#Utilize o looop while para processar enquanto a variável offset for diferente de zero.
while not offset == 0:
 #Dentro do loop while decrementa a variável offset em 1 e print esta.
  offset = offset - 1
  print(offset)

9
8
7
6
5
4
3
2
1
0