<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/kauan_lima/aula_10_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [16]:
brics = pd.read_csv("brics.csv", index_col = 0)
print(brics)

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [19]:
brics["population"]

country_ab
BR     200.40
RU     143.50
IN    1252.00
CH    1357.00
SA      52.98
Name: population, dtype: float64

In [20]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [18]:
brics["area"]>8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [23]:
is_huge=brics["area"]>8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

Pratique

In [27]:
cars = pd.read_csv("/content/cars (1).csv", index_col=0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [37]:
#1
dr = cars["drives_right"]==True
sel = cars[dr]
sel

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [34]:
#2
dr = cars.loc[cars["drives_right"]==True, ["drives_right"]]
print(dr)

            drives_right
country_ab
US                  True
RU                  True
MOR                 True
EG                  True

In [40]:
#3
cars[cars["drives_right"]==True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [41]:
cars[cars["cars_per_cap"]<100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

Loop While

In [42]:
error= 50.0
while error > 1:
  error= error/4
  print(error)

12.5
3.125
0.78125

Pratique

In [43]:
#1, 2 e 3
offset = 10
while offset != 0:
 offset = offset -1
 print(offset)

9
8
7
6
5
4
3
2
1
0