<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Kemilly_Mota/aula10_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
dict = {
    "Country" :["Brazil","Russia","India", "China","South Africa"],
    "Capital" : ["Brasilia","Moscow","New Delhi","Beijing","Pretoria"],
    "Area" : [8.516,17.10,3.286,9.597,1.221],
    "Population" :  [200.40,143.5,1252,1357,52.98]}

In [ ]:
import pandas as pd
brics = pd.DataFrame(dict)
brics
brics.index = ["BR","RU","IN","CH","SA"]
brics

         Country    Capital    Area  Population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
#slide 121
names = ["United States", "Australia","Japan","India","Russia","Marroco","Egypt"]
dr = [True,False,False,False,True,True,True]
cpc = [809,731,588,18,200,70,45]


#importar pandas
import pandas as pd

#criar um dicionário
my_dict = {
    "Country":names,
    "Drivers_right": dr,
    "Cars_per_cap" : cpc
 }

#criar um dataframe
cars = pd.DataFrame(my_dict)
print(cars)

         Country  Drivers_right  Cars_per_cap
0  United States           True           809
1      Australia          False           731
2          Japan          False           588
3          India          False            18
4         Russia           True           200
5        Marroco           True            70
6          Egypt           True            45

In [ ]:
#slide 122
#slide 121
names = ["United States", "Australia","Japan","India","Russia","Marroco","Egypt"]
dr = [True,False,False,False,True,True,True]
cpc = [809,731,588,18,200,70,45]


#importar pandas
import pandas as pd

#criar um dicionário
my_dict = {
    "Country":names,
    "Drivers_right": dr,
    "Cars_per_cap" : cpc
 }

#criar um dataframe
cars = pd.DataFrame(my_dict)
cars


#definir nova tabela
row_lables = ["US","AUS","JPN","IN","RU","MOR","EG"]
cars.index = row_lables
cars

           Country  Drivers_right  Cars_per_cap
US   United States           True           809
AUS      Australia          False           731
JPN          Japan          False           588
IN           India          False            18
RU          Russia           True           200
MOR        Marroco           True            70
EG           Egypt           True            45

In [ ]:
import pandas as pd
cars = pd.read_csv("/content/sample_data/cars.csv")
cars

  country_ab  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

In [ ]:
import pandas as pd
cars = pd.read_csv("/content/sample_data/cars.csv", index_col = 0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
brics["Country"]
type(brics["Country"])

pandas.core.series.Series

In [ ]:
brics[["Country"]]
type(brics)

pandas.core.frame.DataFrame

In [ ]:
brics[["Country","Capital"]]

         Country    Capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [ ]:
brics[1:4] #ACESSAR POR MEIO DOS NÚMEROS

   Country    Capital    Area  Population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
brics.loc["RU"] #ACESSAR LINHA

Country       Russia
Capital       Moscow
Area            17.1
Population     143.5
Name: RU, dtype: object

In [ ]:
brics.iloc[[1,2,3]] #ACESSAR LINHA pelo nome

   Country    Capital    Area  Population
RU  Russia     Moscow  17.100       143.5
IN   India  New Delhi   3.286      1252.0
CH   China    Beijing   9.597      1357.0

In [ ]:
brics.loc[["RU","IN","CH"],["Country", "Capital"]]

   Country    Capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
brics.loc[:,["Country","Capital"]]

         Country    Capital
BR        Brazil   Brasilia
RU        Russia     Moscow
IN         India  New Delhi
CH         China    Beijing
SA  South Africa   Pretoria

In [ ]:
brics.loc[["RU"]]
brics.iloc[[1]]

   Country Capital  Area  Population
RU  Russia  Moscow  17.1       143.5

In [ ]:
brics.iloc[[1,2,3],[0,1]]

   Country    Capital
RU  Russia     Moscow
IN   India  New Delhi
CH   China    Beijing

In [ ]:
from sklearn.datasets import load_wine