<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/david_lucasgs/Aula_17_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
brics = pd.read_csv('brics.csv', index_col=0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [4]:
for val in brics:
    print(val)

country
capital
area
population

In [5]:
for lab, row in brics.iterrows():
    print(lab)
    print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object

In [6]:
for lab, row in brics.iterrows():
  print(lab + ": " + row["capital"])

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria

criar nova coluna

In [7]:
brics.loc[lab, "name_lenght"] = len(row["country"])
print(brics)

                 country    capital    area  population  name_lenght
country_ab
BR                Brazil   Brasilia   8.516      200.40          NaN
RU                Russia     Moscow  17.100      143.50          NaN
IN                 India  New Delhi   3.286     1252.00          NaN
CH                 China    Beijing   9.597     1357.00          NaN
SA          South Africa   Pretoria   1.221       52.98         12.0

aplicar resultado da função em uma coluna nova (substituir)

In [8]:
brics["name_langht"] = brics["country"].apply(len)
print(brics)

                 country    capital    area  population  name_lenght  \
country_ab
BR                Brazil   Brasilia   8.516      200.40          NaN
RU                Russia     Moscow  17.100      143.50          NaN
IN                 India  New Delhi   3.286     1252.00          NaN
CH                 China    Beijing   9.597     1357.00          NaN
SA          South Africa   Pretoria   1.221       52.98         12.0

            name_langht
country_ab
BR                    6
RU                    6
IN                    5
CH                    5
SA                   12

In [40]:
def apply(check_areas):
    if area > 8:
        return "big place"
    else:
        return "small place"
    brics["country_size"] = brics["area"].apply(apply)
    print(brics)

Pratica slide 182

In [10]:
import pandas as pd

In [11]:
cars = pd.read_csv('cars.csv', index_col = 0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [12]:
for lab, row in cars.iterrows():
    print(lab)
    print(row)

US
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object

Pratica slide 183

In [13]:
import pandas as pd

In [14]:
cars = pd.read_csv('cars.csv', index_col = 0)
for lab, row in cars.iterrows():
    print(lab)
    print(row)

US
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object

In [15]:
for lab, row in cars.iterrows():
  print(lab + ": " + str(row["cars_per_cap"]))

US: 809
AUS: 731
JAP: 588
IN: 18
RU: 200
MOR: 70
EG: 45

Pratica slide 184

In [16]:
import pandas as pd

In [17]:
cars = pd.read_csv('cars.csv', index_col = 0)

In [18]:
cars.loc[lab, "name_lenght"] = len(row["country"])
print(brics)

                 country    capital    area  population  name_lenght  \
country_ab
BR                Brazil   Brasilia   8.516      200.40          NaN
RU                Russia     Moscow  17.100      143.50          NaN
IN                 India  New Delhi   3.286     1252.00          NaN
CH                 China    Beijing   9.597     1357.00          NaN
SA          South Africa   Pretoria   1.221       52.98         12.0

            name_langht
country_ab
BR                    6
RU                    6
IN                    5
CH                    5
SA                   12

Pratica slide 185

In [29]:
import pandas as pd

In [36]:
cars = pd.read_csv('cars.csv', index_col = 0)

In [43]:
for lab, row in cars.iterrows():
  cars["COUNTRY"] = cars["country"].apply(str.upper)
  print(cars)

            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT
            cars_per_cap        country  drives_right        COUNTRY
country_ab
US                   809  United States          True  UNITED STATES
AUS                  731      Australia         False      AUSTRALIA
JAP                  588          Japan         False          JAPAN
IN                    18          India         False          INDIA
RU                   200         Russia          True         RUSSIA
MOR                   70        Morocco          True        MOROCCO
EG                    45          Egypt          True          EGYPT

s

In [30]:
import numpy as np

In [31]:
np.random.rand()

0.28613933495037946

In [32]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [33]:
np.random.rand()

0.28613933495037946

In [34]:
coin = np.random.randint(0,2)
print(coin)

0

In [35]:
coin = np.random.randint(0,2)
if coin == 0:
    print("heads")
else:
    print("tails")

heads