<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PANDAS

*CRIANDO UM DATA FRAME*

In [ ]:
dict = {'country':['Brazil', 'Russia', 'India', 'China', 'South Africa'],
        'capital':['Brasilia', 'Moscow', 'New Delhi', 'Beijing', 'Pretoria'],
           'area':[8.516, 17.10, 3.286, 9.597, 1.221],
     'population':[200.4, 143.5, 1252, 1357, 52.98]}

In [ ]:
import pandas as pd
brics = pd.DataFrame(dict)
brics

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Delhi   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98

In [ ]:
brics.index = ['BR', 'RU', 'IN', 'CH', 'SA']
brics #irá modificar a listagem para as suas respectivas iniciais.

         country    capital    area  population
BR        Brazil   brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv')
brics #1

  country_ab       country    capital    area  population
0         BR        Brazil   Brasilia   8.516      200.40
1         RU        Russia     Moscow  17.100      143.50
2         IN         India  New Delhi   3.286     1252.00
3         CH         China    Beijing   9.597     1357.00
4         SA  South Africa   Pretoria   1.221       52.98

In [ ]:
brics = pd.read_csv('/content/brics.csv', index_col = 0)
brics #2

#index_col = 0 retira o index (numeração) de cada linha.

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

#PRATIQUE

1) Importe a biblioteca pandas como pd.

2) Crie um dicionário chamado my_dict considerando 3 chaves:
a - key 'country' e value names.

b - key 'drives_right'  e value dr.

c - key 'cars_per_cap' and value cpc.

3) Crie um dataframe chamado cars a partir do dicionário.

4) Print cars.

In [ ]:
#PRE-DEFINED LISTS
names = ['United States', 'Australia', 'Japan', 'India', 'Russia',
         'Morocco', 'Egypt']
dr = [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]

#IMPORT PANDAS AS PD
import pandas as pd

#CREATE DICTIONARY my_dict WITH THREE KEY: value pairs: my_dict
my_dict = {'country':names,
           'drives_right':dr,
           'cars_per_cap':cpc} #sem transformar em string.

#BUILD A DataFrame CARS FROM my_dict: cars
cars = pd.DataFrame(my_dict)

#PRINT cars
print(cars)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

1) Especifique a coluna index baseada na lista row_labels.

2) Print cars novamente.

In [ ]:
import pandas as pd

#BUILD cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia',
         'Morocco', 'Egypt']
dr = [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
cars_dict = {'country':names,
           'drives_right':dr,
           'cars_per_cap':cpc}
cars = pd.DataFrame(cars_dict)
print(cars)

#DIFINITION OF row_labels
row_labels = ['US', 'AUS', 'JPMN', 'IN', 'RU', 'MOR', 'EG']

#SPECIFY row labels OF cars
cars.index = row_labels

#PRINT cars AGAIN
print(cars)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45
            country  drives_right  cars_per_cap
US    United States          True           809
AUS       Australia         False           731
JPMN          Japan         False           588
IN            India         False            18
RU           Russia          True           200
MOR         Morocco          True            70
EG            Egypt          True            45

1) Adicione este arquivo .csv na página do colab.
https://drive.google.com/file/d/1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo/view?usp=sharing

2) Importe a biblioteca pandas.

3) Crie uma variável cars e leia o arquivo .csv

4) Print cars.

In [ ]:
#IMPORT PANDAS AS PD
import pandas as pd

#IMPORT THE cars.csv DATA: cars
cars = pd.read_csv('/content/cars.csv')

#PRINT OUT cars
print(cars)

  country_ab  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

1) Corrija a leitura do .csv incluindo o index_col = 0.

In [ ]:
#IMPORT PANDAS AS PD
import pandas as pd

#FIX IMPORT BY INCLUDING index_col
cars = pd.read_csv('/content/cars.csv', index_col = 0)

#PRINT OUT cars
print(cars)

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True