<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/Kemilly_Mota/aula11ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics["area"]>8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = brics["area"] > 8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
populacao = brics["population"] > 1000
brics[populacao]

           country    capital   area  population
country_ab
IN           India  New Delhi  3.286      1252.0
CH           China    Beijing  9.597      1357.0

In [ ]:
import pandas as pd
cars = pd.read_csv("/content/sample_data/cars (4).csv",index_col = 0 )
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
dr=cars["drives_right"] == True
print(cars[dr])

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
sel = cars[dr]
print(sel)

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars["drives_right"] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars["cars_per_cap"] < 100] #mostrar cars por cap

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

In [ ]:
erro = 50
while erro > 1:
      erro = erro/4
      print(erro)

12.5
3.125
0.78125

In [ ]:
offset = 11
while offset != 0:
      offset = offset - 1
      print(offset)

10
9
8
7
6
5
4
3
2
1
0

In [ ]:
fam = [1.73,1.68,1.71,1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89

In [ ]:
fam = [1.73,1.68,1.71,1.89]
for index,height in enumerate(fam):
  print("Index" + str(index) + ":" +str(height))

Index0:1.73
Index1:1.68
Index2:1.71
Index3:1.89

In [ ]:
areas = [11.25,18.0,20.0,10.75,9.50]
for area in areas:
  print(area)

11.25
18.0
20.0
10.75
9.5

In [ ]:
areas = [11.25,18.0,20.0,10.75,9.50]
for index,area in enumerate(areas):
  print("Index " + str(index) + ": " +str(area))

Index 0: 11.25
Index 1: 18.0
Index 2: 20.0
Index 3: 10.75
Index 4: 9.5

In [ ]:
house =[["hallway",11.25],
        ["Kitchen", 18.0],
        ["Living room",20.0],
        ["Bedroom",10.75],
        ["Bathroom",9.50]]

for index,casa in(house):
  print("the", index, "is", casa,"sqm")

the hallway is 11.25 sqm
the Kitchen is 18.0 sqm
the Living room is 20.0 sqm
the Bedroom is 10.75 sqm
the Bathroom is 9.5 sqm

In [ ]:
house =[["hallway",11.25],
        ["Kitchen", 18.0],
        ["Living room",20.0],
        ["Bedroom",10.75],
        ["Bathroom",9.50]]
for index, casa in enumerate(house):
  print("the " + str(casa[0] + " is " +str(casa[1]) + " sqm"))

the hallway is 11.25 sqm
the Kitchen is 18.0 sqm
the Living room is 20.0 sqm
the Bedroom is 10.75 sqm
the Bathroom is 9.5 sqm

In [ ]:
world = {"Afeghanistan": 30.55,
         "Albania": 2.77,
         "Algeria" :39.21}
for key, value in world.items():
  print(key + "--" + str(value))

Afeghanistan--30.55
Albania--2.77
Algeria--39.21

In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
bmi = np_weight/np_height**2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856

In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas = np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]

In [ ]:
import numpy as np
np_height = np.array([1.73,1.68,1.71,1.89,1.79])
np_weight = np.array([65.4,59.2,63.6,88.4,68.7])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7

In [ ]:
europe = {"spain": "madrid","france": "paris","germany": "berlin","norway": "oslo","italy": "rome","poland": "warsaw","austria": "vienna"}
for pais, value in europe.items():
  print("the capital of "+ pais+ " is " +str(value))

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna

In [ ]:
import numpy as np
numeros = np.array([1,2,3,4,5,6,7,8,9,10])
numeros1 = np.array([11,12,13,14,15,16,17,18,19,20])

conjunto = np.array([numeros, numeros1])
for val in np.nditer(conjunto):
  print(val)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

In [ ]:
numeros = np.array([1,2,3,4,5,6,7,8,9,10])
numeros1 = np.array([11,12,13,14,15,16,17,18,19,20])

conjunto = np.array([numeros, numeros1])
for val in (conjunto):
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv",index_col = 0)
for val in brics:
  print(val)

country
capital
area
population

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
for lab, row in brics.iterrows():
  print(lab)
  print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
for lab, row in brics.iterrows():
  print(lab+ ":" + row ["capital"])

BR:Brasilia
RU:Moscow
IN:New Delhi
CH:Beijing
SA:Pretoria

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
for lab, row in brics.iterrows():
  brics.loc[lab, "name_lenght"] = len(row["country"])
print(brics)

                 country    capital    area  population  name_lenght
country_ab
BR                Brazil   Brasilia   8.516      200.40          6.0
RU                Russia     Moscow  17.100      143.50          6.0
IN                 India  New Delhi   3.286     1252.00          5.0
CH                 China    Beijing   9.597     1357.00          5.0
SA          South Africa   Pretoria   1.221       52.98         12.0

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
brics["name_lenght"] = brics["country"].apply(len)
print(brics)

                 country    capital    area  population  name_lenght
country_ab
BR                Brazil   Brasilia   8.516      200.40            6
RU                Russia     Moscow  17.100      143.50            6
IN                 India  New Delhi   3.286     1252.00            5
CH                 China    Beijing   9.597     1357.00            5
SA          South Africa   Pretoria   1.221       52.98           12

In [ ]:
def check_area(area):
  if area < 8:
    return "país pequeno"
  else:
    return "país grande"

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
brics["area_check"] = brics["area"].apply(check_area)
print(brics)

                 country    capital    area  population    area_check
country_ab
BR                Brazil   Brasilia   8.516      200.40   país grande
RU                Russia     Moscow  17.100      143.50   país grande
IN                 India  New Delhi   3.286     1252.00  país pequeno
CH                 China    Beijing   9.597     1357.00   país grande
SA          South Africa   Pretoria   1.221       52.98  país pequeno

In [ ]:
import pandas as pd
cars = pd.read_csv("/content/sample_data/cars (4).csv", index_col = 0)
for lab, row in cars.iterrows():
  print(lab + ":", cars)

US:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
AUS:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
JAP:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
IN:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
RU:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
MOR:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
EG:             cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
import pandas as pd
cars = pd.read_csv("/content/sample_data/cars (4).csv", index_col = 0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
import pandas as pd
brics = pd.read_csv("/content/sample_data/brics (1).csv", index_col = 0)
for lab, row in brics.iterrows():
  print(lab)
  print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object

In [ ]:
import numpy as np
np.random.rand()

0.8723887547310428

In [ ]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [ ]:
np.random.rand()

0.28613933495037946

In [ ]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)

0

In [ ]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)
if coin == 0:
  print("heads")
else:
  print("tails")

0
heads