<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/levi_nascimento/Aula_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Filtragem de Elementos com Pandas

In [ ]:

import pandas as pd

brics = pd.read_csv('/content/sample_data/brics.csv', index_col = 0 )
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics["area"] > 8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
brics["population"] > 1000

country_ab
BR    False
RU    False
IN     True
CH     True
SA    False
Name: population, dtype: bool

In [ ]:
is_huge = brics["population"] > 1000

In [ ]:
brics[is_huge]

           country    capital   area  population
country_ab
IN           India  New Delhi  3.286      1252.0
CH           China    Beijing  9.597      1357.0

PRATIQUE

In [ ]:
import pandas as pd

cars = pd.read_csv('/content/sample_data/cars (1).csv', index_col = 0)

#1)Utilize o operador booleano para armazenar a análise da coluna drives_right. Análise de quando a coluna possui valores True. Armazene o conjunto boleano em dr.

dr = cars['drives_right'] == True

#2)Utilize o elemento booleano dr para selecionar a somente os dados True e armazene em um novo dataframe sel e print.

sel = cars[dr]
print(sel)

#3)Converta a filtragem para um código de 1 linha e print a resposta.
cars[cars['drives_right'] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars['cars_per_cap'] < 100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

LOOP WHILE

In [ ]:
#1)crie uma variável offset. Inicialize ela igual 10.

offset = 10

#Utilize o looop while para processar enquanto a variável offset for diferente de zero.
#Dentro do loop while decrementa a variável offset em 1 e print esta.
while offset != 0:
  offset -= 1
  print(offset)

10
9
8
7
6
5
4
3
2
1

LOOP FOR

In [1]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89

In [3]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
  print("index " + str(index) + ": " + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89

PRATIQUE

In [4]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#print cada item da lista areas utilizando o loop for.

for area in areas:
  print(area)

11.25
18.0
20.0
10.75
9.5

In [5]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# mude o loop utilizando a função enumerate para exibir o item e o index do item também.

for index, area in enumerate(areas):
  print("index ", index, ":", area)

index  0 : 11.25
index  1 : 18.0
index  2 : 20.0
index  3 : 10.75
index  4 : 9.5

In [8]:
#implemente um loop for para exibir a seguinte saída :

house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

for ambiente, espaco in (house):
  print("the "+ ambiente + " is "+ str(espaco) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm

In [12]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

for index, espaco in enumerate(house):
  print("the "+ espaco[0] + " is "+ str(espaco[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm

LOOP EM DICIONÁRIO

In [14]:
world = {"afeganistão": 30.55,
         "albania": 2.77,
         "algeria": 39.21}

for key, value in world.items():
  print(key + "--" + str(value))

afeganistão--30.55
albania--2.77
algeria--39.21

LOOP EM NUMPY

In [15]:
import numpy as np
np_height = np.array ([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight/np_height**2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856

In [16]:
import numpy as np

np_height = np.array ([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array ([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]

In [17]:
import numpy as np

np_height = np.array ([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array ([np_height, np_weight])
for val in np.nditer(meas): #np.nditer falar um por um
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7

PRATIQUE

In [19]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsay',
          'austria':'vienna'}

#com auxílio do loop for proporcione  seguinte saída :
for key, value in europe.items():
  print('the capital of ' + key + " is "+ value)

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsay
the capital of austria is vienna

In [22]:
#Crie um array 2D em que possui duas linhas: a primeira é o conjunto dos números de 1 até 10 e a segunda é o conjunto dos números de 11 a 20.
#Com auxilio do loop for mostre cada linha separada
#Com auxilio do loop for mostre cada elemento de cada linha.7

import numpy as np

linha_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
linha_2 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
valores = np.array([linha_1, linha_2])

for val in(valores):
  print(val)

for val in np.nditer(valores):
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20