<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/david_lucasgs/Aula_10_07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
brics = pd.read_csv("brics.csv", index_col = 0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
brics["area"]

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics["area"] > 8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = brics['area'] > 8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
brics[brics["area"] > 8]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

PRATICA 162

1)

In [ ]:
import pandas as pd

In [ ]:
cars = pd.read_csv("cars.csv", index_col = 0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
dr = cars["drives_right"] = True
dr

True

In [ ]:
dr = cars["drives_right"]
sel = cars[dr]
sel

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia          True
JAP                  588          Japan          True
IN                    18          India          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

2)

In [ ]:
dr = cars["drives_right"]
pd.DataFrame = sel
sel = cars[dr]
sel

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia          True
JAP                  588          Japan          True
IN                    18          India          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

3)

In [ ]:
cars[cars["drives_right"] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia          True
JAP                  588          Japan          True
IN                    18          India          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

cars per cap < 100

In [ ]:
cars[cars["cars_per_cap"] < 100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India          True
MOR                   70  Morocco          True
EG                    45    Egypt          True

In [ ]:
erro = 50
while erro > 1:
    erro = erro / 4
    print(erro)

12.5
3.125
0.78125

PRATICA SLIDE 163

In [ ]:
offset = 10
while offset != 0:
    print("correcting...")
    offset = offset - 1
    print(offset)

correcting...
9
correcting...
8
correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0