<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/joao_pedro/Aula_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
brics = pd.read_csv("/content/brics .csv", index_col=0)
brics

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
is_huge = brics[brics['area'] > 8]
is_huge

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

In [ ]:
cars = pd.read_csv("/content/cars.csv", index_col = 0)
cars

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
h = cars[cars['drives_right'] == True]
h

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars['drives_right'] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
df_cars = cars.loc[cars['drives_right'] == True, ['drives_right']]
df_cars

            drives_right
country_ab
US                  True
RU                  True
MOR                 True
EG                  True

In [ ]:
cars[cars['cars_per_cap'] < 100]

            cars_per_cap  country  drives_right
country_ab
IN                    18    India         False
MOR                   70  Morocco          True
EG                    45    Egypt          True

In [ ]:
erro = 50
while erro > 1:
    erro = erro/4
    print(erro)

12.5
3.125
0.78125

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for hight in fam:
    print(hight)

1.73
1.68
1.71
1.89

In [ ]:
for index, height in enumerate(fam):
    print("index " + str(index) + ": " + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89

In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.5]
for area in areas:
    print(area)

11.25
18.0
20.0
10.75
9.5

In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.5]
for index,area in enumerate(areas):
    print("Index " + str(index) + ": " + str(area))

Index 0: 11.25
Index 1: 18.0
Index 2: 20.0
Index 3: 10.75
Index 4: 9.5

In [ ]:
house = [
    ["hallway", 11.25],
    ["kitchen", 18.0],
    ["living room", 20.0],
    ["bedroom", 10.75],
    ["bathroom", 9.50]
]
for room in house:
    print("The " + str(room[0]) + " is " + str(room[1]) + " sqm")

The hallway is 11.25 sqm
The kitchen is 18.0 sqm
The living room is 20.0 sqm
The bedroom is 10.75 sqm
The bathroom is 9.5 sqm

In [ ]:
import numpy as np

In [ ]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
    print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856

In [ ]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas):
    print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'austria':'vienna'}
for key, value in europe.items():
  print(f"The capital of {key} is {value}")

The capital of spain is madrid
The capital of france is paris
The capital of germany is berlin
The capital of norway is oslo
The capital of italy is rome
The capital of poland is warsaw
The capital of austria is vienna

In [ ]:
l1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l2 = [11,12,13,14,15,16,17,18,19,20]
np_num = np.array([l1, l2])
print(np_num)
for val in np.nditer(np_num):
  print(val)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20