<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/gabriel_coelho/aula12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#FILTRAGEM DE ELEMENTO COM PANDAS

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
print(brics)

                 country    capital    area  population
country_ab
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [ ]:
brics['area']

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [ ]:
brics['area'] > 8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [ ]:
is_huge = brics['area'] > 8
brics[is_huge]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

*Tudo em uma única linha*

In [ ]:
brics[brics['area'] > 8]

           country   capital    area  population
country_ab
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

#PRATIQUE

1) Utilize o operador booleano para armazenar a análise da coluna drives_right. Análise de quando a coluna possui valores True. Armazene o conjunto boleano em dr.

2) Utilize o elemento booleano dr para selecionar a somente os dados True e armazene em um novo dataframe sel e print.

3) Converta a filtragem para um código de 1 linha e print a resposta.

In [ ]:
#IMPORT CARS DATA
import pandas as pd
cars = pd.read_csv('/content/cars.csv', index_col = 0)
cars

#EXTRACT DRIVES_RIGHT COLUMN AS SERIES: dr
dr = cars['drives_right'] == True

#USE dr TO SUBSET CARS: sel
sel = cars[dr]

#PRINT sel
print(sel)

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

In [ ]:
cars[cars['drives_right'] == True]

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

#LOOP WHILE

*while* condição:

expressão

In [ ]:
error = 50
while error > 1:
  error = error / 4
  print(error)

12.5
3.125
0.78125

1) Crie uma variável offset. Inicialize ela igual 10.

2) Utilize o looop while para processar enquanto a variável offset for diferente de zero.

3) Dentro do loop while decrementa a variável offset em 1 e print esta.

In [ ]:
#INITIALIZE OFFSET
offset = 10

#CODE THE WHILE LOOP
while offset != 0:
  offset = offset - 1
  print(offset)

9
8
7
6
5
4
3
2
1
0

#LOOP FOR

*for* var *in* seq:

expressão

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89

In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam): #exclusivo para listas.
  print('index ' + str(index) + ': ' + str(height))

index 0: 1.73
index 1: 1.68
index 2: 1.71
index 3: 1.89

#PRATIQUE

1) Print cada item da lista areas utilizando o loop for.

In [ ]:
#AREAS LIST
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#CODE THE for LOOP
for val in areas:
  print(val)

11.25
18.0
20.0
10.75
9.5

 1) Mude o loop utilizando a função enumerate para exibir o item e o index do item também.

In [ ]:
#AREAS LIST
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

#CHANGE for LOOP TO USE ENUMERATE() AND UPDATE PRINT()
for index, area in enumerate(areas):
  print('index '+ str(index) + ': ' + str(area))

index 0: 11.25
index 1: 18.0
index 2: 20.0
index 3: 10.75
index 4: 9.5

1) Implemente um loop for para exibir a seguinte saída :

In [ ]:
#HOUSE LIST OF LISTS
house = [['hallway', 11.25],
         ['kitchen', 18.0],
         ['1living room', 20.0],
         ['bedroom', 10.75],
         ['bathroom', 9.50]]

#BUILD A for LOOP FROM SCRATCH
for index, house in enumerate(house):
  print('the ' + str(house[0]) + ' is ' + str(house[1]) + ' sqm')

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the 1living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm

#LOOP EM DICIONÁRIO

In [ ]:
world = {'afghanistan': 30.55,
         'albania': 2.77,
         'algeria': 39.21}
for key, value in world:
  print(key + ' -- ' + str(value)) #irá apresentar um ERRO,

ValueError: too many values to unpack (expected 2)

In [ ]:
world = {'afghanistan': 30.55,
         'albania': 2.77,
         'algeria': 39.21}
for key, value in world.items():
  print(key + ' -- ' + str(value))

afghanistan -- 30.55
albania -- 2.77
algeria -- 39.21

#LOOP EM NUMPY

In [ ]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856

#LOOP EM NUMPY 2D

In [ ]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]

In [ ]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7

#PRATIQUE

Com auxílio do loop for proporcione  seguinte saída :

In [ ]:
#DEFINITION OD DICTIONARY
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'austria':'vienna'}

#ITERATE OVER EUROPE
for key, value in europe.items(): #exclusivo para dicionários.
  print('the capital of ' + key + ' is ' + str(value))

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna

1) Crie um array 2D em que possui duas linhas: a primeira é o conjunto dos números de 1 até 10 e a segunda é o conjunto dos números de 11 a 20.

2) Com auxilio do loop for mostre cada linha separada.

3) Com auxilio do loop for mostre cada elemento de cada linha.

In [ ]:
import numpy as np
np_array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
np_array2 = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
meas = np.array([np_array1, np_array2])
for val in meas:
  print(val)

for val in np.nditer(meas):
  print(val)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20

#LOOP EM DATAFRAMA

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
for val in brics:
  print(val)

country
capital
area
population

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
for lab, row in brics.iterrows():
  print(lab)
  print(row)

BR
country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
RU
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
IN
country           India
capital       New Delhi
area              3.286
population       1252.0
Name: IN, dtype: object
CH
country         China
capital       Beijing
area            9.597
population     1357.0
Name: CH, dtype: object
SA
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
for lab, row in brics.iterrows():
  print(lab + ': ' + row['capital']) #irá retornar apenas as capitais dos países.

BR: Brasilia
RU: Moscow
IN: New Delhi
CH: Beijing
SA: Pretoria

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
for lab, row in brics.iterrows():
  #CREATING SERIES ON EVERY ITERATION
  brics.loc[lab, 'name_length'] = len(row['country']) #criando uma nova coluna com o tamanho do nome da string.
print(brics)

                 country    capital    area  population  name_length
country_ab
BR                Brazil   Brasilia   8.516      200.40          6.0
RU                Russia     Moscow  17.100      143.50          6.0
IN                 India  New Delhi   3.286     1252.00          5.0
CH                 China    Beijing   9.597     1357.00          5.0
SA          South Africa   Pretoria   1.221       52.98         12.0

In [ ]:
#APLLY
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
brics['name_length'] = brics['country'].apply(len) #aplicando uma função dentro de uma coluna. substitui: len(row).
print(brics)

                 country    capital    area  population  name_length
country_ab
BR                Brazil   Brasilia   8.516      200.40            6
RU                Russia     Moscow  17.100      143.50            6
IN                 India  New Delhi   3.286     1252.00            5
CH                 China    Beijing   9.597     1357.00            5
SA          South Africa   Pretoria   1.221       52.98           12

#FAZENDO UMA FUNÇÃO def (cheque_area) QUE RETORNE 2 POSSIBILIDADES:
1 - PAÍS PEQUENO, SE AREA > 8

2 - PAÍS GRANDE, CASO CONTRÁRIO

In [ ]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
def cheque_area (area):
  if area < 8:
    return 'PAÍS PEQUENO'
  else:
    return 'PAÍS GRANDE'
brics['cheque_area'] = brics['area'].apply(cheque_area)
print(brics)

                 country    capital    area  population   cheque_area
country_ab
BR                Brazil   Brasilia   8.516      200.40   PAÍS GRANDE
RU                Russia     Moscow  17.100      143.50   PAÍS GRANDE
IN                 India  New Delhi   3.286     1252.00  PAÍS PEQUENO
CH                 China    Beijing   9.597     1357.00   PAÍS GRANDE
SA          South Africa   Pretoria   1.221       52.98  PAÍS PEQUENO

#APPLY

In [32]:
import pandas as pd
brics = pd.read_csv('/content/brics.csv', index_col = 0)
brics['name_length'] = brics['country'].apply(len)
print(brics)

                 country    capital    area  population  name_length
country_ab
BR                Brazil   Brasilia   8.516      200.40            6
RU                Russia     Moscow  17.100      143.50            6
IN                 India  New Delhi   3.286     1252.00            5
CH                 China    Beijing   9.597     1357.00            5
SA          South Africa   Pretoria   1.221       52.98           12

#PRATIQUE

1) Com auxilio do loop for mostre cada coluna separadamente do dataframe cars.

2) Com auxílio do loop for realize uma iteraçao nas linhas mostrando a linha id e os elemento contidos de cada linha do dataframe.

In [ ]:
#IMPORT CARS DATA
import pandas as pd
cars = pd.read_csv('/content/cars.csv', index_col = 0)

#ITERATE OVER ROWS OF CARS
for index in cars:
  print(cars)

            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
            cars_per_cap        country  drives_right
country_ab
US                   809  United States          True
AUS                  731      Australia         False
JAP                  588          Japan         False
IN                    18          India         False
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True

1) Altere o código ao lado para que a seguinte saída seja mostrada:

In [37]:
#IMPORT CARS DATA
import pandas as pd
cars = pd.read_csv('/content/cars.csv', index_col = 0)

#ADAPT FOR LOOP
for lab, row in cars.iterrows():
  print(lab, ': ' + str(row))

US : cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS : cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP : cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN : cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU : cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR : cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG : cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object

#GERAÇÃO DE NÚMEROS RANDOM

In [ ]:
import numpy as np
np.random.rand() #irá variar.

0.9943054679489917

In [ ]:
np.random.seed(123) #mesmo valor, pois adicionamos .SEED
np.random.rand()

0.6964691855978616

In [ ]:
np.random.rand() #valor aleaório.

0.5501156705176771

In [ ]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)

0

In [39]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)
if coin == 0:
  print('heads')
else:
  print('tails')

0
heads